--- pgvector 확장 설치 ---
CREATE EXTENSION IF NOT EXISTS vector;

--- 배열 교집합 연산에 대한 function 사전 정의 ---
CREATE OR REPLACE FUNCTION array_overlap(bigint[], bigint[]) RETURNS boolean AS $$
SELECT $1 && $2;
$$ LANGUAGE sql IMMUTABLE;

--- db schema DDL ---
create table public.users (
                              user_id uuid primary key not null,
                              created_at timestamp(6) without time zone not null,
                              updated_at timestamp(6) without time zone not null,
                              email character varying(255) not null,
                              is_verified boolean not null,
                              last_login_at timestamp(6) without time zone,
                              login_type character varying(255) not null,
                              password_hash character varying(255),
                              user_type character varying(255) not null
);
create unique index uk6dotkott2kjsp8vw4d0m25fb7 on users using btree (email);

create table public.foreigner_profile (
                                          foreigner_id uuid primary key not null,
                                          created_at timestamp(6) without time zone not null,
                                          updated_at timestamp(6) without time zone not null,
                                          last_login_at timestamp(6) with time zone,
                                          nickname character varying(255),
                                          profile_object_key character varying(255),
                                          status character varying(255),
                                          user_id uuid
);

create table public.agent_profile (
                                      agent_id uuid primary key not null,
                                      created_at timestamp(6) without time zone not null,
                                      updated_at timestamp(6) without time zone not null,
                                      additional_history character varying(255),
                                      agent_birth date not null,
                                      agent_business_time character varying(255) not null,
                                      agent_comment character varying(255),
                                      license_inner_page_no character varying(255),
                                      license_issued_at date,
                                      license_management_no character varying(255),
                                      license_no character varying(255),
                                      agent_name character varying(255) not null,
                                      office_address character varying(255) not null,
                                      detail_address character varying(255) not null,
                                      office_name character varying(255) not null,
                                      user_id uuid not null,
                                      profile_object_key character varying(255) not null,
                                      active_score double precision not null,
                                      last_login_at timestamp(6) without time zone,
                                      reconnected_at timestamp(6) without time zone,
                                      phone_number character varying(255)
);
create index idx_agent_name_id on agent_profile using btree (agent_name, agent_id);
create index idx_agent_office_address on agent_profile using btree (office_address);
create index idx_agent_active_score_id on agent_profile using btree (active_score, agent_id);


create table public.job_group (
                                  job_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  job_group_name character varying(255),
                                  created_at timestamp(6) without time zone not null,
                                  updated_at timestamp(6) without time zone not null
);
create unique index uk1tcimcnvw2qo8ivpeyxtmvskw on job_group using btree (job_group_name);

create table public.job_code (
                                 job_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 created_at timestamp(6) without time zone not null,
                                 updated_at timestamp(6) without time zone not null,
                                 code character varying(255),
                                 embedding_result vector(512),
                                 name character varying(255),
                                 job_group_id bigint,
                                 foreign key (job_group_id) references public.job_group (job_group_id)
                                     match simple on update no action on delete no action
);

create table public.language (
                                 language_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 value character varying(255),
                                 created_at timestamp with time zone not null,
                                 updated_at timestamp with time zone not null
);

create table public.nationality (
                                    nationality_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    value character varying(255),
                                    created_at timestamp(6) without time zone not null,
                                    updated_at timestamp(6) without time zone not null
);


create table public.agent_review (
                                     agent_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at timestamp(6) without time zone not null,
                                     updated_at timestamp(6) without time zone not null,
                                     agent_profile_id uuid,
                                     feedback_content text,
                                     foreigner_profile_id uuid,
                                     proposal_id bigint not null,
                                     similarity_list double precision[]
);
create unique index ukmgd7lk4r572odr6i3hn5n0df on agent_review using btree (proposal_id);

create table public.badge (
                              badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              created_at timestamp(6) without time zone not null,
                              updated_at timestamp(6) without time zone not null,
                              badge_name character varying(255)
);

create table public.agent_badge (
                                    agent_badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    created_at timestamp(6) without time zone not null,
                                    updated_at timestamp(6) without time zone not null,
                                    agent_review_id bigint not null,
                                    badge_id bigint not null,
                                    foreign key (badge_id) references public.badge (badge_id)
                                        match simple on update no action on delete no action,
                                    foreign key (agent_review_id) references public.agent_review (agent_review_id)
                                        match simple on update no action on delete no action
);

create table public.agent_badge_summary (
                                            agent_badge_summary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            created_at timestamp(6) without time zone not null,
                                            updated_at timestamp(6) without time zone not null,
                                            agent_id uuid not null,
                                            count integer not null,
                                            badge_id bigint not null,
                                            foreign key (badge_id) references public.badge (badge_id)
                                                match simple on update no action on delete no action
);
create unique index uk_agent_badge_combination on agent_badge_summary using btree (agent_id, badge_id);

create table public.agent_language (
                                       agent_language_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       created_at timestamp(6) without time zone not null,
                                       updated_at timestamp(6) without time zone not null,
                                       agent_id uuid,
                                       language_id bigint,
                                       foreign key (language_id) references public.language (language_id)
                                           match simple on update no action on delete no action,
                                       foreign key (agent_id) references public.agent_profile (agent_id)
                                           match simple on update no action on delete no action
);
create index idx_agent_language_code_agent on agent_language using btree (language_id, agent_id);
create index idx_language_agent_id on agent_language using btree (agent_id);

create table public.agent_specialized_job (
                                              agent_specialized_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              created_at timestamp(6) without time zone not null,
                                              updated_at timestamp(6) without time zone not null,
                                              agent_id uuid not null,
                                              job_code_id bigint,
                                              foreign key (job_code_id) references public.job_code (job_code_id)
                                                  match simple on update no action on delete no action,
                                              foreign key (agent_id) references public.agent_profile (agent_id)
                                                  match simple on update no action on delete no action
);
create index idx_specialized_job_code_agent on agent_specialized_job using btree (job_code_id, agent_id);
create index idx_specialized_agent_id on agent_specialized_job using btree (agent_id);

create table public.agent_specialized_job_summary (
                                                      agent_specialized_job_summary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      created_at timestamp(6) without time zone not null,
                                                      updated_at timestamp(6) without time zone not null,
                                                      accumulated_review_reliability double precision not null,
                                                      agent_id uuid not null,
                                                      count integer not null,
                                                      job_code_id bigint not null,
                                                      foreign key (job_code_id) references public.job_code (job_code_id)
                                                          match simple on update no action on delete no action
);
create unique index uk_agent_jobcode_combination on agent_specialized_job_summary using btree (agent_id, job_code_id);

create table public.chat_room (
                                  chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  created_at timestamp(6) without time zone not null,
                                  updated_at timestamp(6) without time zone not null,
                                  last_chatted_at timestamp(6) with time zone not null,
                                  status character varying(255) not null,
                                  agent_id uuid not null,
                                  foreigner_id uuid not null,
                                  foreign key (foreigner_id) references public.foreigner_profile (foreigner_id)
                                      match simple on update no action on delete no action,
                                  foreign key (agent_id) references public.agent_profile (agent_id)
                                      match simple on update no action on delete no action
);

create table public.chat_message (
                                     chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at timestamp(6) without time zone not null,
                                     updated_at timestamp(6) without time zone not null,
                                     content text not null,
                                     is_read_by_other boolean not null,
                                     message_type character varying(255) not null,
                                     sender_id uuid not null,
                                     sent_at timestamp(6) with time zone not null,
                                     chat_room_id bigint not null,
                                     foreign key (chat_room_id) references public.chat_room (chat_room_id)
                                         match simple on update no action on delete no action
);

create table public.foreigner_careers (
                                          career_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          created_at timestamp(6) without time zone not null,
                                          updated_at timestamp(6) without time zone not null,
                                          company_name character varying(255),
                                          end_date date,
                                          foreigner_id uuid,
                                          is_work boolean,
                                          job_title character varying(255),
                                          start_date date
);

create table public.foreigner_education (
                                            foreigner_education_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            created_at timestamp(6) without time zone not null,
                                            updated_at timestamp(6) without time zone not null,
                                            degree_level character varying(255),
                                            foreigner_id uuid,
                                            major_name character varying(255),
                                            school_name character varying(255)
);

create table public.foreigner_expected_company (
                                                   expected_company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   created_at timestamp(6) without time zone not null,
                                                   updated_at timestamp(6) without time zone not null,
                                                   company_name character varying(255),
                                                   foreigner_id uuid,
                                                   job_title character varying(255),
                                                   start_date date
);

create table public.foreigner_language (
                                           foreigner_language_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           created_at timestamp(6) without time zone not null,
                                           updated_at timestamp(6) without time zone not null,
                                           foreigner_id uuid,
                                           language_id bigint,
                                           foreign key (language_id) references public.language (language_id)
                                               match simple on update no action on delete no action,
                                           foreign key (foreigner_id) references public.foreigner_profile (foreigner_id)
                                               match simple on update no action on delete no action
);

create table public.foreigner_nationality (
                                              foreigner_nationality_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              created_at timestamp(6) without time zone not null,
                                              updated_at timestamp(6) without time zone not null,
                                              foreigner_id uuid,
                                              nationality_id bigint,
                                              foreign key (nationality_id) references public.nationality (nationality_id)
                                                  match simple on update no action on delete no action,
                                              foreign key (foreigner_id) references public.foreigner_profile (foreigner_id)
                                                  match simple on update no action on delete no action
);

create table public.foreigner_similarity (
                                             foreigner_similarity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             created_at timestamp(6) without time zone not null,
                                             updated_at timestamp(6) without time zone not null,
                                             foreigner_id uuid,
                                             job_code_id_list bigint[],
                                             similarity_list double precision[]
);

create table public.proposal (
                                 proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 created_at timestamp(6) without time zone not null,
                                 updated_at timestamp(6) without time zone not null,
                                 sender_id uuid not null,
                                 status character varying(255) not null,
                                 chat_room_id bigint not null,
                                 foreign key (chat_room_id) references public.chat_room (chat_room_id)
                                     match simple on update no action on delete no action
);

create table public.visa_application_form (
                                              application_form_id uuid primary key not null,
                                              created_at timestamp(6) without time zone not null,
                                              updated_at timestamp(6) without time zone not null,
                                              contact_information json,
                                              current_step integer not null,
                                              education json,
                                              employment json,
                                              help_information json,
                                              invite_information json,
                                              is_done boolean not null,
                                              is_once_exported boolean not null,
                                              marital_status_and_family_details json,
                                              passport_information json,
                                              personal_detail json,
                                              visit_information json,
                                              total_count integer,
                                              agent_id uuid not null,
                                              foreigner_id uuid not null,
                                              job_code_id bigint not null,
                                              foreign key (agent_id) references public.agent_profile (agent_id)
                                                  match simple on update no action on delete no action,
                                              foreign key (foreigner_id) references public.foreigner_profile (foreigner_id)
                                                  match simple on update no action on delete no action,
                                              foreign key (job_code_id) references public.job_code (job_code_id)
                                                  match simple on update no action on delete no action
);
