export const nationList = [
  "알제리",
  "아르헨티나",
  "호주",
  "방글라데시",
  "브라질",
  "캐나다",
  "칠레",
  "중국",
  "콜롬비아",
  "덴마크",
  "이집트",
  "에티오피아",
  "핀란드",
  "프랑스",
  "독일",
  "가나",
  "홍콩",
  "인도",
  "이란",
  "이라크",
  "이스라엘",
  "이탈리아",
  "일본",
  "카자흐스탄",
  "케냐",
  "대한민국",
  "쿠웨이트",
  "키르기스스탄",
  "멕시코",
  "몽골",
  "모로코",
  "네팔",
  "네덜란드",
  "뉴질랜드",
  "나이지리아",
  "노르웨이",
  "파키스탄",
  "페루",
  "카타르",
  "러시아",
  "사우디아라비아",
  "남아프리카공화국",
  "캄보디아",
  "인도네시아",
  "라오스",
  "말레이시아",
  "미얀마",
  "필리핀",
  "싱가포르",
  "태국",
  "베트남",
  "스페인",
  "스리랑카",
  "스웨덴",
  "타지키스탄",
  "영국",
  "대만",
  "튀니지",
  "튀르키예",
  "우크라이나",
  "아랍에미리트",
  "미국",
  "우즈베키스탄",
];

// 따로 국적에 대해서 기획으로부터 받은 데이터가 없음 >> 우선 구현하고 받는거로 할 생각
export const nationByCategory: {
  name: string;
  items: string[];
}[] = [
  {
    name: "동아시아",
    items: ["일본", "중국", "대만", "홍콩", "몽골"],
  },
  {
    name: "동남아시아",
    items: ["베트남", "태국", "필리핀", "인도네시아", "말레이시아", "싱가포르", "캄보디아", "라오스", "미얀마"],
  },
  {
    name: "남아시아",
    items: ["인도", "방글라데시", "네팔", "파키스탄", "스리랑카"],
  },
  {
    name: "중앙아시아",
    items: ["카자흐스탄", "키르기스스탄", "타지키스탄", "우즈베키스탄"],
  },
  {
    name: "중동",
    items: ["사우디아라비아", "이란", "이라크", "이스라엘", "아랍에미리트", "카타르", "쿠웨이트", "튀르키예"],
  },
  {
    name: "유럽",
    items: [
      "영국",
      "프랑스",
      "독일",
      "이탈리아",
      "스페인",
      "네덜란드",
      "덴마크",
      "핀란드",
      "노르웨이",
      "스웨덴",
      "러시아",
      "우크라이나",
    ],
  },
  {
    name: "아프리카",
    items: ["알제리", "이집트", "에티오피아", "가나", "케냐", "나이지리아", "모로코", "튀니지", "남아프리카공화국"],
  },
  {
    name: "아메리카",
    items: ["미국", "캐나다", "브라질", "아르헨티나", "멕시코", "칠레", "콜롬비아", "페루"],
  },
  {
    name: "오세아니아",
    items: ["호주", "뉴질랜드"],
  },
];

export const englishNationList = [
  "Algeria",
  "Argentina",
  "Australia",
  "Bangladesh",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Denmark",
  "Egypt",
  "Ethiopia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Hongkong",
  "India",
  "Iran",
  "Iraq",
  "Israel",
  "Italy",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Mexico",
  "Mongolia",
  "Morocco",
  "Nepal",
  "Netherlands",
  "NewZealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Qatar",
  "Russia",
  "SaudiArabia",
  "SouthAfrica",
  "SouthCambodia",
  "SouthIndonesia",
  "SouthLaos",
  "SouthMalaysia",
  "SouthMyanmar",
  "SouthPhilippines",
  "SouthSingapore",
  "SouthThailand",
  "SouthVietnam",
  "Spain",
  "SriLanka",
  "Sweden",
  "Tajikistan",
  "theUnitedKingdom",
  "Tiwan",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "UnitedArabEmirates",
  "USA",
  "Uzbekistan",
];

export const nationMap = englishNationList.reduce(
  (acc, eng, idx) => {
    acc[eng] = nationList[idx];
    return acc;
  },
  {} as Record<string, string>,
);
