spring:
  config:
    activate:
      on-profile: remote

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    schemas: public
    clean-disabled: true # 실수를 방지하기 위해 clean 기능 비활성화
    validate-on-migrate: true # 체크섬을 비교하여 기존 파일 변경 시 에러 발생
    locations: classpath:db/migration
    connect-retries: 3

  data:
    redis:
      host: 10.0.138.33
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true