spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # 개발 편의를 위해 update (테이블 자동 변경)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true