spring:
  application:
    name: BE

  profiles:
    active: local

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  config:
    import: optional:file:.env[.properties]

google:
  gemini:
    api:
      base-url: https://generativelanguage.googleapis.com/v1beta/models/
      key: ${GEMINI_API_KEY}