import { useState } from "react";

export const useSearchQuery = <T>() => {
  const [data, _setData] = useState<T[]>();
  const [hasNextPage, _setHasNextPage] = useState(true);
  const [isFetchingNextPage, _setIsFetchingNextPage] = useState(false);

  const fetchNextPage = () => {
    if (hasNextPage && !isFetchingNextPage) console.log("do some");
  };
  const dummyAgentData = dummyA;
  const dummyForeignerData = dummyF;
  return {
    data,
    fetchNextPage,
    dummyAgentData,
    dummyForeignerData,
  };
};

const dummyA = [
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례1",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례2",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례3",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례4",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례5",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례6",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
  {
    id: 2,
    img: "https://placehold.co/140x140",
    name: "엄경례",
    address: "서울특별시 강남구",
    jobs: [1, 4, 6, 2],
    badges: [3, 6],
  },
];
const dummyF = [
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 3,
    nations: [0, 1, 2, 3, 4, 5],
    nickName: "닉 주디 엘리자베스 마야",
    targetJob: "웹 개발자",
    major: "컴퓨터공학",
    languages: [0, 1, 2, 3, 4, 5],
  },
];
