services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: navisa-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: navisa_db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - navisa-network

  redis:
    image: redis:7-alpine
    container_name: navisa-redis
    ports:
      - "6379:6379"
    networks:
      - navisa-network

networks:
  navisa-network:
    driver: bridge